In [1]:
import torch
import torch.nn as nn

In [78]:
max = nn.MaxPool2d(2, stride=1)

In [79]:
test= torch.randn(1, 1, 2, 2)

In [80]:

print(test)
print(max(test))

tensor([[[[-0.0578, -0.8006],
          [ 0.2048, -0.9039]]]])
tensor([[[[0.2048]]]])


In [45]:
conv = nn.Conv2d(1, 1, 2, stride=1, padding=0)

In [46]:
conv.weight.data
conv.bias.data

tensor([0.1024])

In [236]:
conv_0 = nn.Conv2d(1, 1, 2, stride=3, padding=0)
conv_1 = nn.Conv2d(1, 1, 2, stride=3, padding=0)
conv_2 = nn.Conv2d(1, 1, 2, stride=3, padding=0)
conv_3 = nn.Conv2d(1, 1, 2, stride=3, padding=0)

print(conv_1.weight)

conv_0.weight.data = torch.tensor([[[[1., -1.], [0, 0.]]]])
conv_0.bias.data = torch.tensor([0.0])
conv_1.weight.data = torch.tensor([[[[0., 1.], [0., 0.]]]])
conv_1.bias.data = torch.tensor([0.0])
conv_2.weight.data = torch.tensor([[[[0., 0.], [0., 1.]]]])
conv_2.bias.data = torch.tensor([0.0])
conv_3.weight.data = torch.tensor([[[[0., 0.], [1., 0.]]]])
conv_3.bias.data = torch.tensor([0.0])

                                  
print(conv_1.weight.data)

Parameter containing:
tensor([[[[ 0.4109,  0.2989],
          [ 0.1574, -0.4215]]]], requires_grad=True)
tensor([[[[0., 1.],
          [0., 0.]]]])


In [235]:
test= torch.randn(1, 1, 7, 7)
print(test)
print(conv_1(test))
result=nn.ReLU()(conv_0(test))+conv_1(test)
result=nn.ReLU()(conv_2(test)-result)+result
result=nn.ReLU()(conv_3(test)-result)+result
print(result)
max = nn.MaxPool2d(2, stride=3)
print(max(test))

tensor([[[[-2.5702, -2.0346,  0.1149,  0.6245,  1.9530, -1.1155,  0.3395],
          [-0.1289,  0.0763, -1.6734,  0.4181, -0.2481, -0.7128,  0.3197],
          [-0.4244, -1.3910, -1.3068, -0.2547,  0.3269, -0.0826,  1.7261],
          [ 0.4131,  0.1685, -0.5353, -1.6717,  1.0125,  1.8941,  0.1133],
          [ 0.7665,  1.0341, -0.2046,  0.6033, -0.2987,  0.7450, -1.4683],
          [-0.5301, -0.6029, -0.5725, -1.7442,  0.4275, -0.4677, -0.9275],
          [ 0.2729, -1.2211,  0.0133, -0.2954,  0.4356, -0.7790,  0.6830]]]])
tensor([[[[-2.0346,  1.9530],
          [ 0.1685,  1.0125]]]], grad_fn=<ConvolutionBackward0>)
tensor([[[[0.0763, 1.9530],
          [1.0341, 1.0125]]]], grad_fn=<AddBackward0>)
tensor([[[[0.0763, 1.9530],
          [1.0341, 1.0125]]]])
