In [2]:
import torch
import torch.nn as nn

In [78]:
max = nn.MaxPool2d(2, stride=1)

In [79]:
test= torch.randn(1, 1, 2, 2)

In [80]:

print(test)
print(max(test))

tensor([[[[-0.0578, -0.8006],
          [ 0.2048, -0.9039]]]])
tensor([[[[0.2048]]]])


In [45]:
conv = nn.Conv2d(1, 1, 2, stride=1, padding=0)

In [46]:
conv.weight.data
conv.bias.data

tensor([0.1024])

In [182]:
dim_1=3
dim_2=3

conv_0 = nn.Conv2d(dim_1, dim_2, 2, stride=2, padding=0, groups=dim_1)
conv_1 = nn.Conv2d(dim_1, dim_2, 2, stride=2, padding=0, groups=dim_1)
conv_2 = nn.Conv2d(dim_1, dim_2, 2, stride=2, padding=0, groups=dim_1)
conv_3 = nn.Conv2d(dim_1, dim_2, 2, stride=2, padding=0, groups=dim_1)

x=torch.randn(1,3, 4, 4)
max = nn.MaxPool2d(2, stride=2)
print(conv_0(x).shape)
print(max(x).shape)
print(conv_0.weight.data.shape)
w_0 = torch.tensor([[[[1., -1.], [0, 0.]]]])
w_1 = torch.tensor([[[[0., 1.], [0, 0.]]]])
w_2 = torch.tensor([[[[0., 0.], [0., 1.]]]])
w_3 = torch.tensor([[[[0., 0.], [1., 0.]]]])
w_0 = w_0.expand(dim_1,-1,-1,-1)
w_1 = w_1.expand(dim_1,-1,-1,-1)
w_2 = w_2.expand(dim_1,-1,-1,-1)
w_3 = w_3.expand(dim_1,-1,-1,-1)


torch.Size([1, 3, 2, 2])
torch.Size([1, 3, 2, 2])
torch.Size([3, 1, 2, 2])


In [ ]:

w_0=torch.zeros(dim_1,2,2)
w_0[0]=torch.tensor([[1., -1.], [0, 0.]])
w_0=w_0.unsqueeze(0)
print(w_0.shape)
w_0=w_0.expand(dim,-1,-1,-1)
w_1=torch.zeros(dim,2,2)
w_1[0]= torch.tensor([[[0., 1.], [0, 0.]]])
w_1 = w_1.unsqueeze(0)
w_1 = w_1.expand(dim,-1,-1,-1)
w_2=torch.zeros(dim,2,2)
w_2[0] = torch.tensor([[0., 0.], [0., 1.]])
w_2 = w_2.unsqueeze(0)
w_2 = w_2.expand(dim,-1,-1,-1)
w_3=torch.zeros(dim,2,2)
w_3[0] = torch.tensor([[[0., 0.], [1., 0.]]])
w_3 = w_3.unsqueeze(0)
w_3 = w_3.expand(dim,-1,-1,-1)




In [183]:


conv_0.weight.data = w_0
conv_0.bias.data =  torch.zeros(dim_1)
conv_1.weight.data = w_1
conv_1.bias.data =  torch.zeros(dim_1)
conv_2.weight.data = w_2
conv_2.bias.data =  torch.zeros(dim_1)
conv_3.weight.data = w_3
conv_3.bias.data =  torch.zeros(dim_1)
print(conv_0.weight.data)


tensor([[[[ 1., -1.],
          [ 0.,  0.]]],


        [[[ 1., -1.],
          [ 0.,  0.]]],


        [[[ 1., -1.],
          [ 0.,  0.]]]])


In [187]:
test= torch.randn(2, dim_1, 4, 4)

print(test)
print(conv_0(test))


tensor([[[[ 1.1957,  0.0905, -0.2607, -0.6108],
          [ 0.6610, -0.2979, -0.1490,  0.9818],
          [-0.0856,  1.7879, -1.2500,  0.5487],
          [ 1.0943, -1.2330, -2.4573,  0.6534]],

         [[ 0.2017, -0.2903, -0.6042, -0.0190],
          [ 1.3801,  0.2791, -0.4849,  0.1368],
          [-0.0174, -0.4244, -0.3610, -0.7576],
          [ 0.0611,  0.7358,  0.5119, -0.5423]],

         [[ 0.4309,  0.4749,  0.5010,  1.1959],
          [-0.8186,  1.5021,  0.3639, -0.9752],
          [-0.7248,  0.6042, -1.1367,  0.2757],
          [ 0.9944,  0.3708, -0.4382, -1.1340]]],


        [[[ 0.8618, -2.1213, -0.9005, -1.9053],
          [-0.0496, -0.4411,  0.2330, -0.1583],
          [ 0.1357, -1.0831,  1.0638,  0.3778],
          [-1.3565,  0.9890, -0.3050, -0.7067]],

         [[-1.8688,  0.9509,  1.2067,  0.3058],
          [-0.3939,  1.4126, -1.1070,  0.1650],
          [-0.1446,  0.3648,  0.3788,  0.7968],
          [-1.7159,  1.2295,  0.4574,  1.4520]],

         [[-2.2674, -2.4445,

In [188]:
result=nn.ReLU()(conv_0(test))+conv_1(test)

result=nn.ReLU()(conv_2(test)-result)+result

result=nn.ReLU()(conv_3(test)-result)+result
#result= result[:,1,:,:].unsqueeze(1)
print(result.shape)
print(result)

torch.Size([2, 3, 2, 2])
tensor([[[[1.1957, 0.9818],
          [1.7879, 0.6534]],

         [[1.3801, 0.1368],
          [0.7358, 0.5119]],

         [[1.5021, 1.1959],
          [0.9944, 0.2757]]],


        [[[0.8618, 0.2330],
          [0.9890, 1.0638]],

         [[1.4126, 1.2067],
          [1.2295, 1.4520]],

         [[0.2703, 0.1034],
          [1.4039, 0.5571]]]], grad_fn=<AddBackward0>)


In [189]:

max = nn.MaxPool2d(2, stride=2)
print(max(test))
print(max(test).shape)

max.kernel_size

tensor([[[[1.1957, 0.9818],
          [1.7879, 0.6534]],

         [[1.3801, 0.1368],
          [0.7358, 0.5119]],

         [[1.5021, 1.1959],
          [0.9944, 0.2757]]],


        [[[0.8618, 0.2330],
          [0.9890, 1.0638]],

         [[1.4126, 1.2067],
          [1.2295, 1.4520]],

         [[0.2703, 0.1034],
          [1.4039, 0.5571]]]])
torch.Size([2, 3, 2, 2])


2

In [179]:
import torch
import torch.nn as nn

# Définition de l'opération de convolution
conv = nn.Conv2d(in_channels=32, out_channels=32, kernel_size=3, groups=32)

# Entrée fictive de taille (batch_size, 32, height, width)
input_data = torch.randn(1, 32, 28, 28)

# Application de l'opération de convolution à l'entrée
output = conv(input_data)

# Vérification de la taille de la sortie
print("Taille de la sortie :", output.size())


Taille de la sortie : torch.Size([1, 32, 26, 26])


In [192]:
x = torch.randn(1, 3, 4, 4)
dim = len(x[0])
print(dim)

3
