In [1]:
import torch
import torch.nn as nn

In [78]:
max = nn.MaxPool2d(2, stride=1)

In [79]:
test= torch.randn(1, 1, 2, 2)

In [80]:

print(test)
print(max(test))

tensor([[[[-0.0578, -0.8006],
          [ 0.2048, -0.9039]]]])
tensor([[[[0.2048]]]])


In [45]:
conv = nn.Conv2d(1, 1, 2, stride=1, padding=0)

In [46]:
conv.weight.data
conv.bias.data

tensor([0.1024])

In [239]:
conv_0 = nn.Conv2d(1, 1, 2, stride=3, padding=0)
conv_1 = nn.Conv2d(1, 1, 2, stride=3, padding=0)
conv_2 = nn.Conv2d(1, 1, 2, stride=3, padding=0)
conv_3 = nn.Conv2d(1, 1, 2, stride=3, padding=0)

print(conv_1.weight)

conv_0.weight.data = torch.tensor([[[[1., -1.], [0, 0.]]]])
conv_0.bias.data = torch.tensor([0.0])
conv_1.weight.data = torch.tensor([[[[0., 1.], [0., 0.]]]])
conv_1.bias.data = torch.tensor([0.0])
conv_2.weight.data = torch.tensor([[[[0., 0.], [0., 1.]]]])
conv_2.bias.data = torch.tensor([0.0])
conv_3.weight.data = torch.tensor([[[[0., 0.], [1., 0.]]]])
conv_3.bias.data = torch.tensor([0.0])

                                  
print(conv_1.weight.data)

Parameter containing:
tensor([[[[-0.4011,  0.1451],
          [-0.4941, -0.0615]]]], requires_grad=True)
tensor([[[[0., 1.],
          [0., 0.]]]])


In [246]:
test= torch.randn(1, 1, 7, 7)
print(test)
print(conv_1(test))
result=nn.ReLU()(conv_0(test))+conv_1(test)

result=nn.ReLU()(conv_2(test)-result)+result

result=nn.ReLU()(conv_3(test)-result)+result
print(result)
max = nn.MaxPool2d(2, stride=3)
print(max(test))


max.kernel_size

tensor([[[[-0.4652,  0.4748, -1.3689,  0.9742,  1.1395,  1.4037,  1.3677],
          [ 0.6018,  0.0333,  0.7171, -1.0906, -0.8700, -0.0243,  0.4931],
          [ 0.3362, -1.8733,  0.2534,  1.2442, -1.1428, -1.2985, -0.5996],
          [ 0.1294,  1.2177, -0.7573, -0.2450,  1.4997, -1.2794,  0.1294],
          [-0.7658,  0.8046, -0.6498,  0.5464, -0.2019, -0.2657,  1.2065],
          [-0.1093,  0.4634,  1.1943, -0.1416,  0.2340, -0.5610,  0.3471],
          [ 0.4020, -1.1221, -1.5641,  2.0360,  0.0713,  0.2636,  0.5974]]]])
tensor([[[[0.4748, 1.1395],
          [1.2177, 1.4997]]]], grad_fn=<ConvolutionBackward0>)
tensor([[[[0.6018, 1.1395],
          [1.2177, 1.4997]]]], grad_fn=<AddBackward0>)
tensor([[[[0.6018, 1.1395],
          [1.2177, 1.4997]]]])


2